# Generated by Django 5.1.6 on 2025-02-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Habit')),
                ('location', models.CharField(default='Anywhere', max_length=50, verbose_name='Location')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('frequency', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Frequency')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Action')),
                ('is_pleasant_habit', models.BooleanField(default=False, verbose_name='is_pleasant')),
                ('award', models.CharField(blank=True, max_length=50, null=True, verbose_name='Award')),
                ('action_time', models.PositiveIntegerField(default=0, verbose_name='Time to act in seconds')),
                ('is_public', models.BooleanField(default=False, verbose_name='is_public')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Connected habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'ordering': ['pk'],
            },
        ),
    ]
